<?php
/* Class autogenerated whith PHPCriteria v1.1 */

/**
 * @Entity(Table="humedad_tierra")
*/
class EntityHumedad_tierra {

	/**
	 * @Id
	 * @Column(Field="id",Type="int(11)",Key="PRI",Null="NO",Default="",Extra="auto_increment")
	*/
	public $id;

	/**
	 * @Column(Field="estado",Type="int(11)",Key="",Null="YES",Default="",Extra="")
	*/
	public $estado;

	/**
	 * @Column(Field="fecha",Type="datetime",Key="",Null="YES",Default="",Extra="")
	*/
	public $fecha;

	function __construct() {}
}
?>