<?php
/* Class autogenerated whith PHPCriteria v1.1 */

/**
 * @Entity(Table="temperatura")
*/
class EntityTemperatura {

	/**
	 * @Id
	 * @Column(Field="id",Type="int(20)",Key="PRI",Null="NO",Default="",Extra="auto_increment")
	*/
	public $id;

	/**
	 * @Column(Field="temperatura",Type="double",Key="",Null="YES",Default="",Extra="")
	*/
	public $temperatura;

	/**
	 * @Column(Field="humedad",Type="double",Key="",Null="YES",Default="",Extra="")
	*/
	public $humedad;

	/**
	 * @Column(Field="fecha",Type="datetime",Key="",Null="YES",Default="",Extra="")
	*/
	public $fecha;

	function __construct() {}
}
?>